# Generated by Django 4.1.3 on 2022-11-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrit_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostmodels',
            name='name',
        ),
    ]
