# Generated by Django 4.1.3 on 2022-11-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrit_api', '0002_remove_blogpostmodels_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodels',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
