# Generated by Django 4.1.3 on 2022-11-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrit_api', '0006_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='telegram',
            field=models.CharField(max_length=200),
        ),
    ]
