# Generated by Django 4.1.3 on 2022-11-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrit_api', '0007_alter_members_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fullname', models.CharField(max_length=150)),
                ('identity', models.CharField(max_length=79)),
                ('project', models.URLField(blank=True, max_length=250, null=True)),
                ('comments', models.TextField()),
            ],
        ),
    ]
