# Generated by Django 4.1.3 on 2022-11-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrit_api', '0008_customer_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_opinion',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
